name: Dyroff
favicon: null
layout_spectrum: 0.31573032308369875
typography_spectrum: 0.3266204143874347
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.31260370439849794
  lightness: 0.07651183451525867
  saturation: 0.10996236186474562
  rhythmicContrast: 0.22602400463074446
purpose: []
