name: Dyroff
favicon: null
layout_spectrum: 0.49651
typography_spectrum: 0.53214
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#57728d'
    - '#31485c'
    - '#242326'
    - '#000000'
    - '#778eae'
  brandStrength: 0.31260370439849794
  lightness: 0.07651183451525867
  saturation: 0.8125
  rhythmicContrast: 0.75
purpose: []
